title: Kuldeep Singh
logo: /assets/img/headshot_circle.png
#show_downloads: true
theme: jekyll-theme-minimal
.logo {
  display: inline-block;
  line-height: 0;
  max-height: 4rem;
  @include flexbox;
  @include align-items(center);
  img {
    max-height: 5rem;
  }
}
